export const DRUM_KIT = [
  { id: 36, name: "Kick", short: "Kick" },
  { id: 38, name: "Snare", short: "Snare" },
  { id: 42, name: "Closed Hi-Hat", short: "cHH" },
  { id: 44, name: "Pedal Hi-Hat", short: "pHH" },
  { id: 46, name: "Open Hi-Hat", short: "oHH" },
  { id: 39, name: "Hand Clap", short: "Clap" },
  { id: 37, name: "Side Stick", short: "Stick" },
  { id: 40, name: "Electric Snare", short: "eSnr" },
  { id: 41, name: "Low Floor Tom", short: "LoTom" },
  { id: 43, name: "High Floor Tom", short: "HiTom" },
  { id: 45, name: "Low Tom", short: "Mid1" },
  { id: 47, name: "Low-Mid Tom", short: "Mid2" },
  { id: 48, name: "High-Mid Tom", short: "Mid3" },
  { id: 50, name: "High Tom", short: "HiTom" },
  { id: 49, name: "Crash Cymbal", short: "Crash" },
  { id: 51, name: "Ride Cymbal", short: "Ride" },
  { id: 52, name: "Chinese Cymbal", short: "China" },
  { id: 55, name: "Splash Cymbal", short: "Splash" },
  { id: 57, name: "Crash Cymbal 2", short: "Crash2" },
  { id: 59, name: "Ride Cymbal 2", short: "Ride2" },
  { id: 56, name: "Cowbell", short: "Cow" },
  { id: 60, name: "Hi Bongo", short: "HiBon" },
  { id: 61, name: "Low Bongo", short: "LoBon" },
  { id: 62, name: "Mute Hi Conga", short: "mCon" },
  { id: 63, name: "Open Hi Conga", short: "oCon" },
  { id: 64, name: "Low Conga", short: "LoCon" },
  { id: 69, name: "Hi Agogo", short: "HiAgo" },
  { id: 70, name: "Low Agogo", short: "LoAgo" },
  { id: 75, name: "Claves", short: "Clav" },
  { id: 76, name: "Hi Wood Block", short: "HiWb" },
  { id: 77, name: "Low Wood Block", short: "LoWb" },
  { id: 78, name: "Mute Cuica", short: "mCui" },
  { id: 79, name: "Open Cuica", short: "oCui" },
  { id: 80, name: "Mute Triangle", short: "mTri" },
  { id: 81, name: "Open Triangle", short: "oTri" },
];
